cms/urls.py
#coding: utf-8
from django.conf.urls import include, url
from . import views
urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^cadastro$', views.cadastro, name='cadastro'),
	url(r'^login$', views.login_view, name='login_view'),
	url(r'^logout$', views.logout_view, name='logout_view'),
	url(r'^listview$', views.imoveis_view, name='imoveis_view'),
	url(r'^cadastro/(?P<pk>\d+)$',views.detail,name='detail'),
]

sisimob/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "Administração do SisImob"
admin.site.site_title = "Site Locação de Imóveis"
admin.site.index_title = "Administração do site locação de Imóveis"

urlpatterns = [
 	url(r'', include('cms.urls', namespace='cms')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/models.py
#coding: utf-8
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.utils.safestring import mark_safe

fs = FileSystemStorage(location='/media')

class Imovel(models.Model):
    nome = models.CharField(max_length=100)
    endereco = models.CharField(max_length=100)
    preco = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to='documents/')

    def image_tag(self):
        return mark_safe('<img src="%s" width="150" height="150" />' % (self.photo.url))

    class Meta:
        verbose_name = "Imóvel"
        verbose_name_plural = "Imóveis"
    def __unicode__(self):
    	return self.nome

cms/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import Imovel
from django import forms
from django.utils.html import strip_tags

class AuthenticateForm(AuthenticationForm):
    username = forms.CharField(widget=forms.widgets.TextInput(attrs={'placeholder': 'usuário'}))
    password = forms.CharField(widget=forms.widgets.PasswordInput(attrs={'placeholder':'senha'}))

    def is_valid(self):
        form = super(AuthenticateForm,self).is_valid()
        for f, error in self.errors.items():
            if f != '__all__':
                self.fields[f].widget.attrs.update({'class': 'error', 'value': strip_tags(error)})
        return form

class ImovelCadastro(forms.ModelForm):
	class Meta:
		model = Imovel
		fields = '__all__'

cms/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.views.generic import ListView
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required
from .forms import AuthenticateForm, ImovelCadastro
from .models import Imovel

def home(request,auth_form=None):
    if request.user.is_authenticated():
        user = request.user
        return render(request, "rent/home.html",{'user':user,  'next_url': '/'})
    else:
        auth_form = auth_form or AuthenticateForm()
        return render(request, "rent/index.html",{'auth_form': auth_form})

@login_required
def cadastro(request):
    if request.method == 'POST':
        return create(request)
    else:
        return new(request)

@login_required
def new(request):
	return render(request, 'rent/cadastro_form.html', {'form': ImovelCadastro()})


@login_required
def create(request):
	form = ImovelCadastro(request.POST, request.FILES)
	if not form.is_valid():
		return render(request, 'rent/cadastro_form.html', {'form': form})
	obj = form.save(commit=False)
	obj.save()
	return HttpResponseRedirect('/cadastro/%d' % obj.pk)


@login_required
def detail(request,pk):
    imovel = get_object_or_404(Imovel, pk=pk)
    context = {'imovel': imovel}
    return render(request, 'rent/detail.html', context)

def logout_view(request):
	logout(request)
	return redirect('/')

def login_view(request):
	if request.method == 'POST':
		login_post(request)
	return redirect('/')

def login_post(request):
	form = AuthenticateForm(data=request.POST)
	if not form.is_valid():
		return render(request, 'rent/home.html', {'form': form})
	login(request, form.get_user())
	return redirect('/')

def imoveis_view(request):
    imoveis = Imovel.objects.all()
    context = {'imoveis': imoveis }
    return render(request, 'rent/listview.html',context)

sisimob/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

def home(request):
     return render(request, "rent/index.html", {})

cms/templates/rent/cadastro_form.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
    <div class="container">
        <h1>Formulário para cadastro novo imóvel</h1>
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">{% csrf_token %} {{ form.non_field_errors }}
            <fieldset>
                <legend>Dados para cadastro</legend>
                <div class="form-group">
                    <p>
                        <label class="col-sm-2 control-label" for="{{ form.nome.id_for_label }}">{{ form.nome.label }}</label>
                        {{ form.nome }} {{ form.nome.errors }}
                    </p>
                </div>
                <div class="form-group">
                    <p>
                        <label class="col-sm-2 control-label" for="{{ form.endereco.id_for_label }}">{{ form.endereco.label }}</label>
                        {{ form.endereco }} {{ form.endereco.errors }}
                    </p>
                </div>
                <div class="form-group">
                    <p>
                        <label class="col-sm-2 control-label" for="{{ form.preco.id_for_label }}">{{ form.preco.label }}</label>
                        {{ form.preco }} {{ form.preco.errors }}
                    </p>
                </div>
                <div class="form-group">
                    <p>
                        <label class="col-sm-2 control-label" for="{{ form.photo.id_for_label }}">{{ form.photo.label }}</label>
                        {{ form.photo }} {{ form.photo.errors }}
                    </p>
                </div>
            </fieldset>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-6">
                    <input class="btn btn-success btn-lg" type="submit" id="btnLogin" value="Cadastrar">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

cms/templates/rent/detail.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
    <div class="container">
        <div class="card" style="width: 20rem;">
            <img class="card-img-top" src={{ imovel.photo.url }} alt="Card image cap">
            <div class="card-block">
                <h3 class="card-title">{{ imovel.nome }}</h4>
                <p class="card-text">{{ imovel.endereco }}</p>
                <p class="card-text">{{ imovel.preco }}</p>
                <a href="{% url 'cms:imoveis_view' %}" class="btn btn-primary btn-lg">Voltar para a lista</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

cms/templates/rent/home.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1>Cadastro de Imóvel</h1>
		<a class="btn btn-primary btn-lg" href="{% url 'cms:cadastro' %}">Novo Registro</a>
		<a class="btn btn-primary btn-lg" href="{% url 'cms:imoveis_view' %}">Listar Imóveis</a>
    </div>
</div>
{% endblock content %}

cms/templates/rent/index.html
{% extends "base.html" %} {% block head_title %}Rent a house{% endblock %} 

{%block login %}
  <form class="navbar-form navbar-right" action="/login" method="post">
  {% csrf_token %}
    {% for field in auth_form %}
        {{ field }}
    {% endfor %}

    <input type="submit" id="btnLogin" value="Log in">
  </form>
{% endblock %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Rent a House</h1>
        <p>Esse site é destinado a fazer busca por casas para alugar, temos o interesse de concorrer com air bed and breakfast</p>
        <p><a class="btn btn-primary btn-lg" href="listview" role="button">Ver lista de imóveis disponíveis &raquo;</a></p>
    </div>
</div>
<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <h2>Fácil</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        </div>
        <div class="col-md-4">
            <h2>Prático</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        </div>
        <div class="col-md-4">
            <h2>Direto</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        </div>
    </div>
    <hr>
</div>
<!-- /container -->
{% endblock %}

cms/templates/rent/listview.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
    <div class="container">
        <h2>Imóveis</h2>
        <ul class="list-group">
            {% for imovel in imoveis %}
            <a href="{% url 'cms:detail' imovel.pk %}">
                <li class="list-group-item">{{ imovel.nome }}</li>
            </a>
            {% empty %}
            <li>Não há imoveis cadastrados.</li>
            {% endfor %}
        </ul>
        <br>
    </div>
</div>
{% endblock %}

sisimob/templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block head_title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
    body {
        padding-top: 50px;
        padding-bottom: 20px;
    }
    </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    {% block head_css %}{% endblock %} {% block head_javascript %}{% endblock %}
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    {% block navbar %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'cms:home' %}">Rent a House</a> 
                {% block login %}
                <a class="navbar-brand" href="{% url 'cms:home' %}">Home</a>
                <form action="/logout">
                    <input type="submit" id="btnLogOut" value="Log Out">
                </form>
                {% endblock %}
                
            </div>
            <!--/.navbar-collapse -->
        </div>
    </nav>
    {% endblock %} {% block content %} {% endblock %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>
    window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')
    </script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
    (function(b, o, i, l, e, r) {
        b.GoogleAnalyticsObject = l;
        b[l] || (b[l] =
            function() {
                (b[l].q = b[l].q || []).push(arguments)
            });
        b[l].l = +new Date;
        e = o.createElement(i);
        r = o.getElementsByTagName(i)[0];
        e.src = '//www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e, r)
    }(window, document, 'script', 'ga'));
    ga('create', 'UA-XXXXX-X', 'auto');
    ga('send', 'pageview');
    </script>
</body>

</html>

sisimob/templates/rent/detail.html
{% extends 'base.html' %} {% block content %}
<div class="jumbotron">
    <div class="container">
        <div class="card" style="width: 20rem;">
            <img class="card-img-top" src={{ imovel.photo.url }} alt="Card image cap">
            <div class="card-block">
                <h3 class="card-title">{{ imovel.nome }}</h4>
                <p class="card-text">{{ imovel.endereco }}</p>
                <p class="card-text">{{ imovel.preco }}</p>
                <a href="/listview" class="btn btn-primary btn-lg">Voltar para a lista</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

sisimob/templates/rent/index.html
{% extends "base.html" %} {% block head_title %}Rent a house{% endblock %} {% block content %}

{%block login %}
  <form class="navbar-form navbar-right" action="/login" method="post">
  {% csrf_token %}
    {% for field in auth_form %}
    {{ field }}
    {% endfor %}

    <input type="submit" id="btnLogin" value="Log in">
  </form>
{% endblock %}
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container">
        <h1>Rent a House</h1>
        <p>Esse site é destinado a fazer busca por casas para alugar, temos o interesse de concorrer com air bed and breakfast</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Ver lista de imóveis disponíveis &raquo;</a></p>
    </div>
</div>
<div class="container">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <h2>Fácil</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        </div>
        <div class="col-md-4">
            <h2>Prático</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        </div>
        <div class="col-md-4">
            <h2>Direto</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        </div>
    </div>
    <hr>
</div>
<!-- /container -->
{% endblock %} {% block footer %}
<footer>
    <center>
        <p>&copy; 2017</p>
    </center>
</footer>
{% endblock %}

sisimob/templates/rent/listview.html
{% extends "base.html" %} {% block content %}
<div class="jumbotron">
    <div class="container">
        <h2>Imóveis</h2>
        <ul class="list-group">
            {% for imovel in imoveis %}
            <a href="/cadastro/{{imovel.pk}}">
                <li class="list-group-item">{{ imovel.nome }}</li>
            </a>
            {% empty %}
            <li>Não há imoveis cadastrados.</li>
            {% endfor %}
        </ul>
        <br>
    </div>
</div>
{% endblock %}